version: "3.9"
services:
  redis:
    image: redis:alpine3.16
    container_name: redis
    ports:
      - "6379:6379"
  web:
    build: .
    container_name: bitcoin-tracker
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    depends_on:
      - redis
